name: smooth_page_indicator
description: Customizable animated page indicator with a set of built-in effects.
version: 1.2.0+3
homepage: https://github.com/Milad-Akarie/smooth_page_indicator
screenshots:
  - description: 'Example of smooth page indicator.'
    path: demo/four_squares_demo.gif
topics:
  - page-indicator
  - dot-indicator
  - indicator
  - page-view

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
